spring:
  data:
    elasticsearch:
      cluster-name: my-application
      cluster-nodes: 172.19.57.211:9300
  application:
    name: sms_task
  datasource:
    name: sms
    url: jdbc:mysql://rm-uf6s0j8g14m247250.mysql.rds.aliyuncs.com:3306/huolika?serverTimezone=GMT%2B8&autoReconnect=true&useUnicode=true&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true&rewriteBatchedStatements=true
    username: huolika_app
    password: huolika@2019
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 4
      max-active: 32
      max-wait: 60000
      min-idle: 4
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 3000
      min-evictable-idle-time-millis: 300000
      pool-prepared-statements: true
      test-while-idle: true
      validation-query: select 1
  redis:
# Redis数据库索引（默认为0）
    database: 6
# Redis服务器地址
    host: 9686e0ac66ee45b2.redis.rds.aliyuncs.com
# Redis服务器连接端口
    port: 6379
# Redis服务器连接密码（默认为空）
    password: 9686e0ac66ee45b2:BeadWallet2016
# 连接超时时间（毫秒）
    timeout: 100000
# 连接池最大连接数（使用负值表示没有限制）
    jedis:
      pool:
        max-active: 500
        max-idle: 5
        min-idle: 1
        max-wait: 100000
sms:
  tryun:
    use-notice: notice
    notice_accesskey: EwdwxAeEcDvFhXWt
    notice-access-secret: fVVXLoayl1fML7pqPJS3OjxRHrRKCZ38
    notice-template-key: sms:tryun:notice_template
    marketing-accesskey: MxGbo0ufqjuzHNIF
    marketing-access-secret: adaMmjkeyBzBtD6uFoPdTpFd2YJAkcPI
    marketing-template-key: sms:tryun:marketing_template
    send-url: http://api.1cloudsp.com/api/v2/send
    report-url: http://api.1cloudsp.com/report/status